### ISSUE TITLE
Firefox: pthread deadlock after hardware error

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#2707]
### Problem Description

I'm using Yubikey 4 OTP+U2F+CCID and Firefox 109 on Ubuntu (pcscd 1.8.26, libccid 1.4.31) and after hibernation I'm sporadically observing that the card doesn't respond anymore, which causes OpenSC/Firefox to run in a deadlock. This makes the browser unusable since it doesn't react anymore.

The last line of the OpenSC log shows that it doesn't return from `sc_lock_mutex`. Debugging into the process, I observe that two threads are actually requesting a lock:
```
Thread 7 (Thread 0x7f5adab55700 (LWP 430926)):
#0  __lll_lock_wait (futex=futex@entry=0x7f5ab90613a0, private=0) at lowlevellock.c:52
#1  0x00007f5aecf31235 in __GI___pthread_mutex_lock (mutex=0x7f5ab90613a0) at ../nptl/pthread_mutex_lock.c:135
#2  0x00007f5aec9bb2f9 in PR_Lock (lock=0x7f5ab90613a0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/nsprpub/pr/src/pthreads/ptsynch.c:176
#3  0x00007f5aebeb4309 in secmodLockMutext (mutext=0x7f5ab90613a0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pk11wrap/pk11load.c:54
#4  0x00007f5abe669942 in sc_pkcs11_lock () at pkcs11-global.c:973
#5  0x00007f5abe6687b8 in C_GetSlotInfo (slotID=0, pInfo=0x7f5adab53f28) at pkcs11-global.c:603
#6  0x00007f5aebecc02c in PK11_GetSlotInfo (slot=0x7f5abd1a4c00, info=info@entry=0x7f5adab53f28) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pk11wrap/pk11slot.c:1926
#7  0x00007f5aebe90859 in nssSlot_IsTokenPresent (slot=0x7f5ad768a030) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/dev/devslot.c:175
#8  0x00007f5aebe90a69 in nssSlot_GetToken (slot=0x7f5ad768a030) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/dev/devslot.c:294
#9  0x00007f5aebe9b50a in nssTrustDomain_FindTrustForCertificate (td=0x7f5abd125030, c=<optimized out>, c@entry=0x7f5a94485888) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pki/trustdomain.c:1063
#10 0x00007f5aebe963b5 in fill_CERTCertificateFields (c=0x7f5a94485888, cc=0x7f5a94499020, forced=<optimized out>) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pki/pki3hack.c:798
#11 stan_GetCERTCertificate (c=c@entry=0x7f5a94485888, forceUpdate=<optimized out>, forceUpdate@entry=0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pki/pki3hack.c:931
#12 0x00007f5aebe96777 in STAN_GetCERTCertificate (c=0x7f5ab90613a0, c@entry=0x7f5a94485888) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pki/pki3hack.c:978
#13 0x00007f5aebe7b241 in CERT_NewTempCertificate (handle=<optimized out>, handle@entry=0x0, derCert=derCert@entry=0x7f5adab54150, nickname=nickname@entry=0x0, isperm=<optimized out>, isperm@entry=0, copyDER=copyDER@entry=1) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/certdb/stanpcertdb.c:417
#14 0x00007f5aebcd3d58 in ssl_DecodeResumptionToken (sid=0x7f5a84ae8f40, encodedToken=encodedToken@entry=0x7f5a890f9b08 "\002", encodedTokenLen=encodedTokenLen@entry=1742) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/ssl/sslnonce.c:512
#15 0x00007f5aebcde75e in SSLExp_SetResumptionToken (fd=<optimized out>, token=0x7f5a890f9b08 "\002", len=1742) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/ssl/sslsock.c:4527
#16 0x00007f5ae55aad8b in NSSSocketControl::SetResumptionTokenFromExternalCache() (this=0x7f5a95e3c400) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/manager/ssl/NSSSocketControl.cpp:648
#17 0x00007f5ae55df416 in nsSSLIOLayerAddToSocket(int, char const*, int, nsIProxyInfo*, mozilla::OriginAttributes const&, PRFileDesc*, nsITLSSocketControl**, bool, unsigned int, unsigned int) (family=<optimized out>, host=<optimized out>, host@entry=0x7f5a89c78328 "alive.github.com", port=0, port@entry=443, proxy=<optimized out>, proxy@entry=0x0, originAttributes=..., fd=fd@entry=0x7f5a953c5e50, tlsSocketControl=0x7f5adab54510, forSTARTTLS=<optimized out>, providerFlags=0, providerTlsFlags=0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/manager/ssl/nsNSSIOLayer.cpp:1630
#18 0x00007f5ae55e5203 in nsSSLIOLayerNewSocket(int, char const*, int, nsIProxyInfo*, mozilla::OriginAttributes const&, PRFileDesc**, nsITLSSocketControl**, bool, unsigned int, unsigned int) (family=<optimized out>, host=0x7f5a89c78328 "alive.github.com", port=443, proxy=0x0, originAttributes=..., fd=<optimized out>, tlsSocketControl=<optimized out>, forSTARTTLS=false, flags=<optimized out>, tlsFlags=<optimized out>) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/manager/ssl/nsNSSIOLayer.cpp:1232
#19 nsSSLSocketProvider::NewSocket(int, char const*, int, nsIProxyInfo*, mozilla::OriginAttributes const&, unsigned int, unsigned int, PRFileDesc**, nsITLSSocketControl**) (this=<optimized out>, family=<optimized out>, host=0x7f5a89c78328 "alive.github.com", port=443, proxy=0x0, originAttributes=..., flags=<optimized out>, tlsFlags=<optimized out>, _result=<optimized out>, tlsSocketControl=<optimized out>) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/manager/ssl/nsSSLSocketProvider.cpp:28
#20 0x00007f5ae1b46eb6 in mozilla::net::nsSocketTransport::BuildSocket(PRFileDesc*&, bool&, bool&) (this=<optimized out>, this@entry=0x7f5a89053400, fd=@0x7f5adab54570: 0x0, proxyTransparent=<optimized out>, usingSSL=<optimized out>) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/netwerk/base/nsSocketTransport2.cpp:1147
#21 0x00007f5ae1b476fc in mozilla::net::nsSocketTransport::InitiateSocket() (this=this@entry=0x7f5a89053400) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/netwerk/base/nsSocketTransport2.cpp:1311
#22 0x00007f5ae1b495be in mozilla::net::nsSocketTransport::OnSocketEvent(unsigned int, nsresult, nsISupports*) (this=0x7f5a89053400, type=1, status=nsresult::NS_OK, param=0x0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/netwerk/base/nsSocketTransport2.cpp:2005
#23 0x00007f5ae1b60d6a in mozilla::net::nsSocketEvent::Run() (this=<optimized out>) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/netwerk/base/nsSocketTransport2.cpp:94
#24 0x00007f5ae1a0759d in nsThread::ProcessNextEvent(bool, bool*) (this=0x7f5aec71fa00, aMayWait=<optimized out>, aResult=0x7f5adab54987) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/xpcom/threads/nsThread.cpp:1198
#25 0x00007f5ae1a0b159 in NS_ProcessNextEvent(nsIThread*, bool) (aThread=0x7f5ab90613a0, aMayWait=true) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/xpcom/threads/nsThreadUtils.cpp:474
#26 0x00007f5ae1b504f2 in mozilla::net::nsSocketTransportService::Run() (this=0x7f5ae0350660) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/netwerk/base/nsSocketTransportService2.cpp:1235
#27 0x00007f5ae1b510bd in non-virtual thunk to mozilla::net::nsSocketTransportService::Run() () at /build/firefox-gaF6Cx/firefox-109.0.1+build1/obj-x86_64-linux-gnu/dist/include/mozilla/ProfilerThreadRegistration.h:355
#28 0x00007f5ae1a0759d in nsThread::ProcessNextEvent(bool, bool*) (this=0x7f5aec71fa00, aMayWait=<optimized out>, aResult=0x7f5adab54b27) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/xpcom/threads/nsThread.cpp:1198
#29 0x00007f5ae1a0b159 in NS_ProcessNextEvent(nsIThread*, bool) (aThread=0x7f5ab90613a0, aThread@entry=0x7f5aec71fa00, aMayWait=false) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/xpcom/threads/nsThreadUtils.cpp:474
#30 0x00007f5ae206a778 in mozilla::ipc::MessagePumpForNonMainThreads::Run(base::MessagePump::Delegate*) (this=0x7f5adf8a1600, aDelegate=0x7f5adab54ba0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/ipc/glue/MessagePump.cpp:300
#31 0x00007f5ae2021818 in MessageLoop::RunInternal() (this=0x80) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/ipc/chromium/src/base/message_loop.cc:381
#32 MessageLoop::RunHandler() (this=0x80) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/ipc/chromium/src/base/message_loop.cc:374
#33 MessageLoop::Run() (this=0x80) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/ipc/chromium/src/base/message_loop.cc:356
#34 0x00007f5ae1a0508e in nsThread::ThreadFunc(void*) (aArg=0x7f5adf89e7c0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/xpcom/threads/nsThread.cpp:383
#35 0x00007f5aec9cafe9 in _pt_root (arg=arg@entry=0x7f5adf7f3040) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/nsprpub/pr/src/pthreads/ptthread.c:201
#36 0x000055fa6f4bc9b0 in set_alt_signal_stack_and_start(PthreadCreateParams*) (params=<optimized out>) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/toolkit/crashreporter/pthread_create_interposer/pthread_create_interposer.cpp:80
#37 0x00007f5aecf2e609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#38 0x00007f5aecb01133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
...
Thread 99 (Thread 0x7f5aa177d700 (LWP 432149)):
#0  __lll_lock_wait (futex=futex@entry=0x7f5ab9090920, private=0) at lowlevellock.c:52
#1  0x00007f5aecf31235 in __GI___pthread_mutex_lock (mutex=0x7f5ab9090920) at ../nptl/pthread_mutex_lock.c:135
#2  0x00007f5aec9bb2f9 in PR_Lock (lock=0x7f5ab9090920) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/nsprpub/pr/src/pthreads/ptsynch.c:176
#3  0x00007f5aebeb4309 in secmodLockMutext (mutext=0x7f5ab9090920) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pk11wrap/pk11load.c:54
#4  0x00007f5abe667a18 in sc_lock_mutex (m=0x7f5ab9090920) at pkcs11-global.c:186
#5  0x00007f5ab72a945e in sc_mutex_lock (ctx=0x7f5ab9086300, mutex=0x7f5ab9090920) at sc.c:1114
#6  0x00007f5ab72b7d9a in sc_lock (card=0x7f5abd13de00) at card.c:473
#7  0x00007f5ab72dd1c0 in sc_pkcs15_get_pin_info (p15card=0x7f5adf5a42e0, pin_obj=0x7f5ab90d3700) at pkcs15-pin.c:709
#8  0x00007f5abe67dcda in slot_get_logged_in_state (slot=0x7f5ab9087200) at framework-pkcs15.c:1391
#9  0x00007f5abe66a474 in C_GetSessionInfo (hSession=140027696134624, pInfo=0x7f5aa177c2c0) at pkcs11-session.c:279
#10 0x00007f5aebe9f19a in PK11_IsLoggedIn (slot=0x7f5abd1abc00, wincx=<optimized out>, wincx@entry=0x0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pk11wrap/pk11auth.c:790
#11 0x00007f5aebe9bae1 in nssSlot_IsLoggedIn (slot=slot@entry=0x7f5ad7686030) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pk11wrap/dev3hack.c:245
#12 0x00007f5aebe930d0 in search_for_objects (cache=0x7f5ab90fe410) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/dev/devutil.c:434
#13 get_token_objects_for_cache (cache=0x7f5ab90fe410, objectType=<optimized out>, objclass=3461563219) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/dev/devutil.c:544
#14 nssTokenObjectCache_FindObjectsByTemplate (cache=0x7f5ab90fe410, objclass=objclass@entry=3461563219, otemplate=otemplate@entry=0x7f5aa177c3f0, otlen=otlen@entry=4, maximumOpt=maximumOpt@entry=1, statusOpt=statusOpt@entry=0x7f5aa177c39c) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/dev/devutil.c:724
#15 0x00007f5aebe90cf5 in nssToken_FindObjectsByTemplate (token=0x7f5ad7684030, sessionOpt=0x7f5abd125320, obj_template=0x7f5aa177c3f0, otsize=4, maximumOpt=maximumOpt@entry=1, statusOpt=statusOpt@entry=0x0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/dev/devtoken.c:398
#16 0x00007f5aebe922fc in nssToken_FindTrustForCertificate (token=0x7f5ab9090920, sessionOpt=<optimized out>, sessionOpt@entry=0x0, certEncoding=certEncoding@entry=0x7f5a729ec920, certIssuer=certIssuer@entry=0x7f5a729ec930, certSerial=certSerial@entry=0x7f5a729ec950, searchType=searchType@entry=nssTokenSearchType_TokenOnly) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/dev/devtoken.c:1128
#17 0x00007f5aebe9b52d in nssTrustDomain_FindTrustForCertificate (td=0x7f5abd125030, c=<optimized out>, c@entry=0x7f5a729ec8c0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pki/trustdomain.c:1066
#18 0x00007f5aebe95d2d in nssTrust_GetCERTCertTrustForCert (c=c@entry=0x7f5a729ec8c0, cc=cc@entry=0x7f5a729d8820) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pki/pki3hack.c:618
#19 0x00007f5aebe9664c in fill_CERTCertificateFields (c=0x7f5a729ec8c0, cc=0x7f5a729d8820, forced=<optimized out>) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pki/pki3hack.c:824
#20 stan_GetCERTCertificate (c=c@entry=0x7f5a729ec8c0, forceUpdate=<optimized out>, forceUpdate@entry=0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pki/pki3hack.c:931
#21 0x00007f5aebe96777 in STAN_GetCERTCertificate (c=0x7f5ab9090920, c@entry=0x7f5a729ec8c0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pki/pki3hack.c:978
#22 0x00007f5aebe99ff8 in add_cert_to_cache (td=0x7f5abd125030, cert=0x7f5a729ec8c0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pki/tdcache.c:720
#23 nssTrustDomain_AddCertsToCache (td=0x7f5abd125030, certs=<optimized out>, certs@entry=0x7f5aa177c610, numCerts=<optimized out>, numCerts@entry=1) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pki/tdcache.c:848
#24 0x00007f5aebe98730 in cert_createObject (o=0x7f5a729ec830) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pki/pkibase.c:1023
#25 0x00007f5aebe987de in nssPKIObjectCollection_GetObjects (collection=0x7f5a729dc030, rvObjects=0x7f5a7d0fe050, rvSize=<optimized out>) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pki/pkibase.c:853
#26 nssPKIObjectCollection_GetCertificates (collection=collection@entry=0x7f5a729dc030, rvOpt=0x7f5a7d0fe050, rvOpt@entry=0x0, maximumOpt=maximumOpt@entry=0, arenaOpt=<optimized out>, arenaOpt@entry=0x0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pki/pkibase.c:1077
#27 0x00007f5aebea2f63 in PK11_TraverseCertsInSlot (slot=<optimized out>, slot@entry=0x7f5abd1a5400, callback=0x7f5aebea3870 <listCertsCallback>, arg=arg@entry=0x7f5aa177c6c0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pk11wrap/pk11cert.c:2375
#28 0x00007f5aebea3840 in PK11_ListCertsInSlot (slot=0x7f5abd1a5400) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/nss/lib/pk11wrap/pk11cert.c:2899
#29 0x00007f5ae55dafd5 in IntermediatePreloadingHealerCallback(nsITimer*, void*) () at /build/firefox-gaF6Cx/firefox-109.0.1+build1/security/manager/ssl/nsNSSComponent.cpp:2049
#30 0x00007f5ae19fff0d in nsTimerImpl::Fire(int)::$_16::operator()(nsTimerImpl::FuncCallback const&) const (this=<optimized out>, f=...) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/xpcom/threads/nsTimerImpl.cpp:661
#31 mozilla::detail::VariantImplementation<unsigned char, 3ul, nsTimerImpl::FuncCallback, nsTimerImpl::ClosureCallback>::matchN<mozilla::Variant<nsTimerImpl::UnknownCallback, nsCOMPtr<nsITimerCallback>, nsCOMPtr<nsIObserver>, nsTimerImpl::FuncCallback, nsTimerImpl::ClosureCallback>&, nsTimerImpl::Fire(int)::$_16, nsTimerImpl::Fire(int)::$_17>(mozilla::Variant<nsTimerImpl::UnknownCallback, nsCOMPtr<nsITimerCallback>, nsCOMPtr<nsIObserver>, nsTimerImpl::FuncCallback, nsTimerImpl::ClosureCallback>&, nsTimerImpl::Fire(int)::$_16&&, nsTimerImpl::Fire(int)::$_17&&) (aV=..., aMi=..., aMs=...) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/obj-x86_64-linux-gnu/dist/include/mozilla/Variant.h:309
#32 mozilla::detail::VariantImplementation<unsigned char, 2ul, nsCOMPtr<nsIObserver>, nsTimerImpl::FuncCallback, nsTimerImpl::ClosureCallback>::matchN<mozilla::Variant<nsTimerImpl::UnknownCallback, nsCOMPtr<nsITimerCallback>, nsCOMPtr<nsIObserver>, nsTimerImpl::FuncCallback, nsTimerImpl::ClosureCallback>&, nsTimerImpl::Fire(int)::$_15, nsTimerImpl::Fire(int)::$_16, nsTimerImpl::Fire(int)::$_17>(mozilla::Variant<nsTimerImpl::UnknownCallback, nsCOMPtr<nsITimerCallback>, nsCOMPtr<nsIObserver>, nsTimerImpl::FuncCallback, nsTimerImpl::ClosureCallback>&, nsTimerImpl::Fire(int)::$_15&&, nsTimerImpl::Fire(int)::$_16&&, nsTimerImpl::Fire(int)::$_17&&) (aV=..., aMi=..., aMs=..., aMs=...) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/obj-x86_64-linux-gnu/dist/include/mozilla/Variant.h:318
#33 mozilla::detail::VariantImplementation<unsigned char, 1ul, nsCOMPtr<nsITimerCallback>, nsCOMPtr<nsIObserver>, nsTimerImpl::FuncCallback, nsTimerImpl::ClosureCallback>::matchN<mozilla::Variant<nsTimerImpl::UnknownCallback, nsCOMPtr<nsITimerCallback>, nsCOMPtr<nsIObserver>, nsTimerImpl::FuncCallback, nsTimerImpl::ClosureCallback>&, nsTimerImpl::Fire(int)::$_14, nsTimerImpl::Fire(int)::$_15, nsTimerImpl::Fire(int)::$_16, nsTimerImpl::Fire(int)::$_17>(mozilla::Variant<nsTimerImpl::UnknownCallback, nsCOMPtr<nsITimerCallback>, nsCOMPtr<nsIObserver>, nsTimerImpl::FuncCallback, nsTimerImpl::ClosureCallback>&, nsTimerImpl::Fire(int)::$_14&&, nsTimerImpl::Fire(int)::$_15&&, nsTimerImpl::Fire(int)::$_16&&, nsTimerImpl::Fire(int)::$_17&&) (aV=..., aMi=..., aMs=..., aMs=..., aMs=...) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/obj-x86_64-linux-gnu/dist/include/mozilla/Variant.h:318
#34 mozilla::detail::VariantImplementation<unsigned char, 0ul, nsTimerImpl::UnknownCallback, nsCOMPtr<nsITimerCallback>, nsCOMPtr<nsIObserver>, nsTimerImpl::FuncCallback, nsTimerImpl::ClosureCallback>::matchN<mozilla::Variant<nsTimerImpl::UnknownCallback, nsCOMPtr<nsITimerCallback>, nsCOMPtr<nsIObserver>, nsTimerImpl::FuncCallback, nsTimerImpl::ClosureCallback>&, nsTimerImpl::Fire(int)::$_13, nsTimerImpl::Fire(int)::$_14, nsTimerImpl::Fire(int)::$_15, nsTimerImpl::Fire(int)::$_16, nsTimerImpl::Fire(int)::$_17>(mozilla::Variant<nsTimerImpl::UnknownCallback, nsCOMPtr<nsITimerCallback>, nsCOMPtr<nsIObserver>, nsTimerImpl::FuncCallback, nsTimerImpl::ClosureCallback>&, nsTimerImpl::Fire(int)::$_13&&, nsTimerImpl::Fire(int)::$_14&&, nsTimerImpl::Fire(int)::$_15&&, nsTimerImpl::Fire(int)::$_16&&, nsTimerImpl::Fire(int)::$_17&&) (aV=..., aMi=..., aMs=..., aMs=..., aMs=..., aMs=...) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/obj-x86_64-linux-gnu/dist/include/mozilla/Variant.h:318
#35 mozilla::Variant<nsTimerImpl::UnknownCallback, nsCOMPtr<nsITimerCallback>, nsCOMPtr<nsIObserver>, nsTimerImpl::FuncCallback, nsTimerImpl::ClosureCallback>::matchN<mozilla::Variant<nsTimerImpl::UnknownCallback, nsCOMPtr<nsITimerCallback>, nsCOMPtr<nsIObserver>, nsTimerImpl::FuncCallback, nsTimerImpl::ClosureCallback>&, nsTimerImpl::Fire(int)::$_13, nsTimerImpl::Fire(int)::$_14, nsTimerImpl::Fire(int)::$_15, nsTimerImpl::Fire(int)::$_16, nsTimerImpl::Fire(int)::$_17>(mozilla::Variant<nsTimerImpl::UnknownCallback, nsCOMPtr<nsITimerCallback>, nsCOMPtr<nsIObserver>, nsTimerImpl::FuncCallback, nsTimerImpl::ClosureCallback>&, nsTimerImpl::Fire(int)::$_13&&, nsTimerImpl::Fire(int)::$_14&&, nsTimerImpl::Fire(int)::$_15&&, nsTimerImpl::Fire(int)::$_16&&, nsTimerImpl::Fire(int)::$_17&&) (aVariant=..., aM0=..., aM1=..., aMs=..., aMs=..., aMs=...) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/obj-x86_64-linux-gnu/dist/include/mozilla/Variant.h:902
#36 mozilla::Variant<nsTimerImpl::UnknownCallback, nsCOMPtr<nsITimerCallback>, nsCOMPtr<nsIObserver>, nsTimerImpl::FuncCallback, nsTimerImpl::ClosureCallback>::match<nsTimerImpl::Fire(int)::$_13, nsTimerImpl::Fire(int)::$_14, nsTimerImpl::Fire(int)::$_15, nsTimerImpl::Fire(int)::$_16, nsTimerImpl::Fire(int)::$_17>(nsTimerImpl::Fire(int)::$_13&&, nsTimerImpl::Fire(int)::$_14&&, nsTimerImpl::Fire(int)::$_15&&, nsTimerImpl::Fire(int)::$_16&&, nsTimerImpl::Fire(int)::$_17&&) & (this=0x7f5aa177c7c0, aM0=..., aM1=..., aMs=..., aMs=..., aMs=...) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/obj-x86_64-linux-gnu/dist/include/mozilla/Variant.h:857
#37 nsTimerImpl::Fire(int) (this=0x7f5adf5a4880, aGeneration=1) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/xpcom/threads/nsTimerImpl.cpp:655
#38 0x00007f5ae19ff99e in nsTimerEvent::Run() (this=0x7f5ad7b40620) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/xpcom/threads/TimerThread.cpp:365
#39 0x00007f5ae19fccda in mozilla::TaskQueue::Runner::Run() (this=0x7f5a7cbedb00) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/xpcom/threads/TaskQueue.cpp:259
#40 0x00007f5ae1a0c88c in nsThreadPool::Run() (this=0x7f5adf60f570) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/xpcom/threads/nsThreadPool.cpp:309
#41 0x00007f5ae1a0759d in nsThread::ProcessNextEvent(bool, bool*) (this=0x7f5a9e127c80, aMayWait=<optimized out>, aResult=0x7f5aa177cb27) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/xpcom/threads/nsThread.cpp:1198
#42 0x00007f5ae1a0b159 in NS_ProcessNextEvent(nsIThread*, bool) (aThread=0x7f5ab9090920, aThread@entry=0x7f5a9e127c80, aMayWait=false) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/xpcom/threads/nsThreadUtils.cpp:474
#43 0x00007f5ae206a778 in mozilla::ipc::MessagePumpForNonMainThreads::Run(base::MessagePump::Delegate*) (this=0x7f5a8b7fe900, aDelegate=0x7f5aa177cba0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/ipc/glue/MessagePump.cpp:300
#44 0x00007f5ae2021818 in MessageLoop::RunInternal() (this=0x80) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/ipc/chromium/src/base/message_loop.cc:381
#45 MessageLoop::RunHandler() (this=0x80) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/ipc/chromium/src/base/message_loop.cc:374
#46 MessageLoop::Run() (this=0x80) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/ipc/chromium/src/base/message_loop.cc:356
#47 0x00007f5ae1a0508e in nsThread::ThreadFunc(void*) (aArg=0x7f5a953c42e0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/xpcom/threads/nsThread.cpp:383
#48 0x00007f5aec9cafe9 in _pt_root (arg=arg@entry=0x7f5a959a75e0) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/nsprpub/pr/src/pthreads/ptthread.c:201
#49 0x000055fa6f4bc9b0 in set_alt_signal_stack_and_start(PthreadCreateParams*) (params=<optimized out>) at /build/firefox-gaF6Cx/firefox-109.0.1+build1/toolkit/crashreporter/pthread_create_interposer/pthread_create_interposer.cpp:80
#50 0x00007f5aecf2e609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#51 0x00007f5aecb01133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### Steps to reproduce

Apply the following patch to OpenSC to simulate a hardware error after successful initialization.
```diff
diff --git a/src/libopensc/reader-pcsc.c b/src/libopensc/reader-pcsc.c
index 40bfd293d..5947bf787 100644
--- a/src/libopensc/reader-pcsc.c
+++ b/src/libopensc/reader-pcsc.c
@@ -240,10 +240,16 @@ static int pcsc_internal_transmit(sc_reader_t *reader,
        DWORD dwSendLength, dwRecvLength;
        LONG rv;
        SCARDHANDLE card;
+       static size_t approx_allowed_apdus = 50;
 
        LOG_FUNC_CALLED(reader->ctx);
        card = priv->pcsc_card;
 
+       if (approx_allowed_apdus > 0)
+               approx_allowed_apdus--;
+       else
+               return SC_ERROR_TRANSMIT_FAILED;
+
        if (reader->ctx->flags & SC_CTX_FLAG_TERMINATE)
                return SC_ERROR_NOT_ALLOWED;
```
Now, start firefox with opensc-pkcs11.so, which should stall the browser very quickly

**Comment by frankmorgner** [comment]
[opensc-debug.txt](https://github.com/OpenSC/OpenSC/files/10734851/opensc-debug.txt)

**Comment by frankmorgner** [comment]
updated the description with a way to reproduce the problem
