### ISSUE TITLE
org.apache.poi.EncryptedDocumentException: java.security.InvalidKeyException: Missing key encoding

### ISSUE THREAD

**Issue by ngocduy96** [OpenSC/OpenSC#3247]
I encountered an EncryptedDocumentException with the message java.security.InvalidKeyException: **Missing key encoding** when attempting to sign a **DOCX** file using **Apache POI** and **PKCS11**. Below are the details of the exception and the relevant code snippet.
> Exception Stack Trace:
```
org.apache.poi.EncryptedDocumentException: java.security.InvalidKeyException: Missing key encoding
    at org.apache.poi.poifs.crypt.dsig.SignatureInfo.signDigest(SignatureInfo.java:279)
    at org.apache.poi.poifs.crypt.dsig.SignatureInfo.confirmSignature(SignatureInfo.java:228)
    at org.example.Main.signDOCX(Main.java:146)
    at org.example.Main.main(Main.java:62)
Caused by: java.security.InvalidKeyException: Missing key encoding
    at java.base/sun.security.rsa.RSAPrivateCrtKeyImpl.newKey(RSAPrivateCrtKeyImpl.java:88)
    at java.base/sun.security.rsa.RSAKeyFactory.translatePrivateKey(RSAKeyFactory.java:314)
    at java.base/sun.security.rsa.RSAKeyFactory.engineTranslateKey(RSAKeyFactory.java:227)
    at java.base/sun.security.rsa.RSAKeyFactory.toRSAKey(RSAKeyFactory.java:130)
    at java.base/sun.security.rsa.RSASignature.engineInitSign(RSASignature.java:112)
    at java.base/sun.security.rsa.RSASignature.engineInitSign(RSASignature.java:104)
    at java.base/java.security.Signature$Delegate.engineInitSign(Signature.java:1370)
    at java.base/java.security.Signature.initSign(Signature.java:635)
    at org.apache.poi.poifs.crypt.dsig.SignatureOutputStream.init(SignatureOutputStream.java:45)
    at org.apache.poi.poifs.crypt.dsig.SignatureInfo.signDigest(SignatureInfo.java:270)
    ... 3 more 
```
    
>  Steps to Reproduce:
1. Load the PKCS#11 provider.
2. Load the key store.
3. Retrieve the private key.
4. Attempt to sign a DOCX file using the following code:
``` 
import org.apache.poi.openxml4j.opc.OPCPackage;
import org.apache.poi.poifs.crypt.dsig.SignatureConfig;
import org.apache.poi.poifs.crypt.dsig.SignatureInfo;
import org.bouncycastle.jce.provider.BouncyCastleProvider;

import java.io.FileOutputStream;
import java.security.KeyStore;
import java.security.PrivateKey;
import java.security.Provider;
import java.security.Security;
import java.security.cert.X509Certificate;
import java.util.Collections;

public class Main {
    private static final String CONFIG_PATH = "src/main/java/org/example/pkcs11.conf";
    private static final String DOCX_INPUT_PATH = "src/main/java/org/example/input.docx";
    private static final String DOCX_OUTPUT_PATH = "src/main/java/org/example/signed_output.docx";
    private static final String PASSKEY = "12345678";

    public static void main(String[] args) {
        try {
            Main mainApp = new Main();
            mainApp.signDOCX();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void signDOCX() throws Exception {
        Security.addProvider(new BouncyCastleProvider());

        Provider sunPKCS11 = loadSunPKCS11Provider();
        KeyStore keyStore = loadKeyStore(sunPKCS11);
        PrivateKey privateKey = getPrivateKey(keyStore);
        X509Certificate certificate = (X509Certificate) keyStore.getCertificate(keyStore.aliases().nextElement());

        SignatureConfig signatureConfig = new SignatureConfig();
        signatureConfig.setKey(privateKey);
        signatureConfig.setSigningCertificateChain(Collections.singletonList(certificate));

        OPCPackage pkg = OPCPackage.open(DOCX_INPUT_PATH);
        SignatureInfo si = new SignatureInfo();
        si.setOpcPackage(pkg);
        si.setSignatureConfig(signatureConfig);

        try {
            si.confirmSignature();
        } catch (Exception e) {
            System.out.println("Error during signature confirmation: " + e.getMessage());
            e.printStackTrace();
        }

        boolean isVerified = si.verifySignature();
        System.out.println("Signature verify: " + isVerified);

        try (FileOutputStream fos = new FileOutputStream(DOCX_OUTPUT_PATH)) {
            pkg.save(fos);
        }
        pkg.close();

        System.out.println("DOCX signed successfully. File saved at: " + DOCX_OUTPUT_PATH);
    }

    private Provider loadSunPKCS11Provider() throws Exception {
        Provider sunPKCS11 = Security.getProvider("SunPKCS11");
        sunPKCS11 = sunPKCS11.configure(CONFIG_PATH);
        Security.addProvider(sunPKCS11);
        return sunPKCS11;
    }

    private KeyStore loadKeyStore(Provider provider) throws Exception {
        KeyStore keyStore = KeyStore.getInstance("PKCS11", provider);
        keyStore.load(null, PASSKEY.toCharArray());
        return keyStore;
    }

    private PrivateKey getPrivateKey(KeyStore keyStore) throws Exception {
        String alias = keyStore.aliases().nextElement();
        return (PrivateKey) keyStore.getKey(alias, PASSKEY.toCharArray());
    }
}   
```
### Why am I getting this error? Please help me.

**Comment by frankmorgner** [comment]
[There is a similar thread with some suggestions ](https://support.nitrokey.com/t/nitrokey-hsm-and-java/2656)from @CardContact , which you might find helpful.

**Comment by frankmorgner** [comment]
Your backtrace indicates that, internally, Java tries to get some encoding of the private key, which is expected to *not* work, because this is a non-exportable key on a hardware token. For reference, browse the related Java code:
https://github.com/openjdk/jdk22/blob/master/src/java.base/share/classes/sun/security/rsa/RSAKeyFactory.java

If you think this could be solved differently or the problem lies somewhere else, please add more info an reopen.
